spring:
  application:
    name: monday
  datasource:
    url: jdbc:postgresql://localhost:54329/student
    username: student
    password: student
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
